#!/bin/bash

if [ ! "$1" ]; then
  echo "create_instance <subnet_ocid>"
  exit 1
fi

ad1=$1
subnet_ocid=$2
echo "Subnet: $subnet_ocid"

# Launch a new compute instance:
export image_ocid=`oci compute image list --shape "VM.Standard2.1" --operating-system "CentOS" --operating-system-version 7 --sort-by TIMECREATED --query data[0].id --config-file ../config --cli-rc-file ../oci_cli_rc | tr -d '"'`
echo $image_ocid

export vm_ocid=`oci compute instance launch --display-name cli-vm-test-1 --availability-domain "$ad1" --subnet-id "$subnet_ocid" --private-ip 192.168.3.2 --image-id "$image_ocid" --shape VM.Standard.E2.1 --ssh-authorized-keys-file ~/.ssh/id_rsa.pub --wait-for-state RUNNING --query data.id --config-file ../config --cli-rc-file ../oci_cli_rc | tr -d '"'`
echo $vm_ocid

# Query for the Public IP address of a compute instance running in a public subnet:
export vm_public_ip=`oci compute instance list-vnics --instance-id "$vm_ocid" --query data[0].\"public-ip\" --raw-output --config-file ../config --cli-rc-file ../oci_cli_rc`
echo $vm_public_ip

