#!/bin/bash

# Create a Password for a User

user_ocid=$1
echo "Creating Password for $user_ocid"
password=`oci iam user ui-password create-or-reset --config-file ../config --user-id $user_ocid --query "data.password" | tr -d '"'`
echo "Your password is: $password"

