#!/bin/bash

# Get a list of all user names

TENANCY_OCID=$(cat ../config | grep tenancy | sed 's/tenancy=//')
echo "Working in tenancy $TENANCY_OCID"
echo "Getting all Users..."

oci iam user list \
  --region us-ashburn-1 \
  --config-file ../config \
  -c "$TENANCY_OCID" \
  --query "data[*].{Name:name,OCID:id}" \
  --all \
  --output table