#!/bin/bash

# Get a List of all User Names and OCIDs for a group

if [ ! "$1" ]; then
  echo "get_group_users <group_name>"
  exit 1
fi

GROUP_NAME="$1"
TENANCY_OCID=$(cat ../config | grep tenancy | sed 's/tenancy=//')
GROUP_OCID=$(oci iam group list \
  --region us-ashburn-1 \
  --config-file ../config \
  -c "$TENANCY_OCID" \
  --all \
  --query "data[?name=='$GROUP_NAME'] | [0].id" \
  | tr -d '"')

echo "Getting all Users for Group $GROUP_NAME"

oci iam group list-users \
  --config-file ../config \
  --group-id "$GROUP_OCID" \
  --query "data[*].{Name:name,OCID:id}" \
  --all \
  --output table
