#!/bin/bash

# List Statements for a Policy

if [ ! "$1" ]; then
  echo "list_policies <policy_name>"
  exit 1
fi
POLICY_NAME="$1"
TENANCY_OCID=$(cat ../config | grep tenancy | sed 's/tenancy=//')

oci iam policy list \
  --config-file ../config \
  -c "$TENANCY_OCID" \
  --all \
  --query "data[?name=='$POLICY_NAME'].statements"