#!/bin/bash

# Remove User

if [ ! "$1" ]; then
  echo "remove_user <user_name>"
  exit 1
fi
USER_NAME=$1
echo "Deleting User $USER_NAME"

TENANCY_OCID=$(cat ../config | grep tenancy | sed 's/tenancy=//')

# Get the User OCID

USER_OCID=$(oci iam user list \
  --config-file ../config \
  -c "$TENANCY_OCID" \
  --query "data[?name=='$USER_NAME'] | [0].id" \
  --all \
  --raw-output \
  )

echo "OCID: $USER_OCID"

oci iam user delete \
  --region us-ashburn-1 \
  --config-file ../config \
  --user-id "$USER_OCID" \
  --wait-for-state DELETED
