#!/bin/bash

# Terminate User
user_ocid=$1
echo "Deleting User $user_ocid"
TENANCY_OCID=`cat ../config | grep tenancy | sed 's/tenancy=//'`
oci iam user delete --region us-ashburn-1 --config-file ../config --user-id $user_ocid
