#!/bin/bash

# Terminate an Instance

if [ ! "$1" ]; then
  echo "terminate_instance <instance_ocid>"
  exit 1
fi
INSTANCE_OCID=$1
echo "Terminating Instance: $INSTANCE_OCID"

oci compute instance terminate \
  --config-file ../config \
  --cli-rc-file ../oci_cli_rc \
  --instance-id $INSTANCE_OCID \
  --wait-for-state TERMINATED
