#!/bin/bash

# Terminate a VCN

if [ ! "$1" ]; then
  echo "terminate_vcn <vcn_ocid>"
  exit 1
fi

VCN_OCID=$1
echo "Terminating VCN: $VCN_OCID"

oci network vcn delete \
  --config-file ../config \
  --vcn-id $VCN_OCID


