#!/bin/bash

# Terminate an Instance
vm_ocid=$1
echo "Terminating Instance: $vm_ocid"
oci compute instance terminate --config-file ../config --cli-rc-file ../oci_cli_rc --instance-id $vm_ocid --wait-for-state TERMINATED
