#!/bin/bash

# Terminate a Group by OCID

if [ ! $1 ]; then
  echo "terminate_group <group_ocid>"
  exit 1
fi

GROUP_OCID="$1"
echo "Terminating Group $GROUP_OCID"

oci iam group delete \
  --region us-ashburn-1 \
  --config-file ../config \
  --group-id $GROUP_OCID \
  --wait-for-state DELETED
